- var:
    theInputFolder: "{{ argv[0] }}" #The input folder (containing sam files)|inFile|Folder,trimmed-seq|Folder|and|
    mirBaseDB: "{{ argv[1] }}" #The database name for miRBase|list|mirna_21a,mirna_22b|||
    ucscGenomeRef: "{{ argv[2] }}" #The UCSC genome short name|list|mm10,hg38|||
    mirBaseSpeciesShortName: "{{ argv[3] }}" #The species short name for miRBase|list|mmu,hsa|||
  batch-items: "{{ var.theInputFolder | listFromFileGlob(['*.sam']) | sort }}"
  task-template:
    name: annotation
    image: "registry.gitlab.com/chiyang/bdp-bcgsc-mirna:0.3"
    exec: perl
    args:
      - /package/scripts/bcgsc-mirna-v0.2.7/code/annotation/chi_annotate.pl
      - -m
      - "{{ var.mirBaseDB }}"
      - -u
      - "{{ var.ucscGenomeRef }}"
      - -o
      - "{{ var.mirBaseSpeciesShortName }}"
      - -s
      - "{{ item | pathMapping }}"
    option:
      net: host