- var:
    theProjectFolder: "{{ argv[0] }}" #The project folder|inFile|Folder|Folder|and|
  task-template:
    name: summarize-annotations
    image: "registry.gitlab.com/chiyang/bdp-bcgsc-mirna:0.3"
    exec: perl
    args:
      - /package/scripts/bcgsc-mirna-v0.2.7/code/library_stats/alignment_stats.pl
      - -p
      - "{{ var.theProjectFolder | pathMapping }}"