- var:
    trimmedSeqFolder: "{{ argv[0] }}" #The folder of trimmed sequence|inFile|Folder,fastq-merged|Folder|and|
    refGenomeFolder: "{{ argv[1] }}" #The reference folder|inFile|Folder,genome,indexed,bwa|Folder|and|
  batch-items: "{{ var.trimmedSeqFolder | listFromFileGlob(['*_trimmed.fq']) | sort }}"
  task-template:
    name: run-bwa
    image: quay.io/biocontainers/bwa:0.7.17--ha92aebf_3
    exec: bwa
    args:
    - aln
    - -t
    - "{{option.cpus}}"
    - -f
    - "{{ var.trimmedSeqFolder | suffix('/' + path.basename(item, '_trimmed.fq') + '.sai') | pathMapping }}" # The output file (*.sai)
    - "{{ var.refGenomeFolder | listFromFileGlob(['*.fa']) | first | pathMapping }}" # The refgenome.fa inside argv[1]
    - "{{ item | pathMapping}}" # The trimmed fastq file.