- var:
    keggSpeciesName: "{{ argv[0] }}"
    ucscGenomeRef: "{{ argv[1] }}"
    gencodeRelease: "{{ argv[2] }}"
    biomartName: "{{ argv[3] }}"
    biomartDataset: "{{ argv[4] }}"
    biomartHost: "{{argv[5]}}"
    outputFolder: "{{argv[6] | ensureDir | pathMapping }}"
    theKEGGpathwayFile: "{{ argv[7] }}"
    theUCSCgenomeSeqFolder: "{{ argv[8] | ensureDir }}"
    targetScanFile: "{{ argv[9] }}"
    genomeAnnotationGtf: "{{ argv[10] }}"
    biomartTable: "{{ argv[11] }}"
  task-template:
    name: download-kegg-pathway
    image: busybox
    exec: /bin/sh
    args:
    - -c
    - "wget -O \"{{var.theKEGGpathwayFile | pathMapping}}\" http://rest.kegg.jp/list/pathway/{{ var.keggSpeciesName }}"
- var:
    targetScanLink: >-
      {%- if var.keggSpeciesName == 'hsa' -%}http://www.targetscan.org/vert_72/vert_72_data_download/Predicted_Targets_Context_Scores.default_predictions.txt.zip
      {%- elif var.keggSpeciesName == 'mmu' -%}http://www.targetscan.org/mmu_72/mmu_72_data_download/Conserved_Site_Context_Scores.txt.zip
      {%- endif -%}
    targetScanFileName: >-
      {%- if var.keggSpeciesName == 'hsa' -%}Predicted_Targets_Context_Scores.default_predictions.txt
      {%- elif var.keggSpeciesName == 'mmu' -%}Conserved_Site_Context_Scores.txt
      {%- endif -%}
    targetScanPrefix: >-
      {%- if var.keggSpeciesName == 'hsa' -%}Human_Ver72_
      {%- elif var.keggSpeciesName == 'mmu' -%}Mouse_Ver72{%- endif -%}
  task-template:
    name: download-targetScanRef
    image: busybox
    exec: /bin/sh
    args:
    - -c
    - >-
      wget \"{{ var.targetScanLink }}\" -O \"/tmp/{{ var.targetScanFileName }}.zip\" &&
      unzip -o \"/tmp/{{ var.targetScanFileName }}.zip\" &&
      mv \"/tmp/{{var.targetScanFileName}}\" \"{{ var.targetScanFile | pathMapping }}\"
    option:
      workdir: /tmp
- - task-template:
      name: download-ucsc
      image: biocontainers/biocontainers
      exec: /bin/sh
      args: 
      - -c
      - >-
        rsync -avzP --max-size=10000000 \"rsync://hgdownload.cse.ucsc.edu/goldenPath/{{ var.ucscGenomeRef }}/database/\" .
      option:
        workdir: "{{ var.outputFolder }}"
  - task-template:
      name: download-ucsc-genome-seq-2bit
      image: biocontainers/biocontainers
      exec: bash
      args:
      - -c
      - >-
        rsync -avzP \"rsync://hgdownload.cse.ucsc.edu/goldenPath/{{var.ucscGenomeRef}}/bigZips/{{var.ucscGenomeRef}}.2bit\" .
      option:
        workdir: "{{ var.theUCSCgenomeSeqFolder | pathMapping }}"
- task-template:
    name: convert-2bit-to-fa
    image: quay.io/biocontainers/ucsc-twobittofa:366--h5eb252a_0
    exec: twoBitToFa
    args:
      - "{{ var.theUCSCgenomeSeqFolder | pathMapping}}/{{var.ucscGenomeRef}}.2bit"
      - "{{ var.theUCSCgenomeSeqFolder | pathMapping}}/{{var.ucscGenomeRef}}.fa"
- task-template:
    name: build-bwa-index
    image: quay.io/biocontainers/bwa:0.7.17--ha92aebf_3
    exec: bwa
    args:
      - index
      - "{{ var.theUCSCgenomeSeqFolder | pathMapping }}/{{var.ucscGenomeRef}}.fa"
- var:
    gencodeFileName: >-
      {%- if var.keggSpeciesName == 'hsa' -%}gencode.v{{ var.gencodeRelease }}.chr_patch_hapl_scaff.annotation.gtf
      {%- elif var.keggSpeciesName == 'mmu' -%}gencode.vM{{ var.gencodeRelease }}.chr_patch_hapl_scaff.annotation.gtf
      {%- endif -%}
    gencodeLink: >-
      {%- if var.keggSpeciesName == 'hsa' -%}http://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_{{ var.gencodeRelease }}
      {%- elif var.keggSpeciesName == 'mmu' -%}http://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M{{ var.gencodeRelease }}
      {%- endif -%}
  task-template:
    name: download-gencode-annotation
    image: busybox
    exec: /bin/sh
    args:
    - -c
    - >-
      wget \"{{ var.gencodeLink }}/{{ var.gencodeFileName}}.gz\" -O \"/tmp/{{ var.gencodeFileName}}.gz\" &&
      gunzip -f \"/tmp/{{ var.gencodeFileName }}.gz\" &&
      mv \"/tmp/{{var.gencodeFileName }}\" \"{{ var.genomeAnnotationGtf | pathMapping }}\"
    option:
      workdir: "/tmp"
# 17. Get BioMart table
- task-template:
    name: get-biomart-table
    image: biocontainers/biocontainers
    exec: wget
    args:
    - -O
    - "{{ var.biomartTable | pathMapping}}"
    - >-
      http://{{ var.biomartHost }}/biomart/martservice?query=<?xml version=\"1.0\" encoding=\"UTF-8\"?><!DOCTYPE Query><Query virtualSchemaName = \"default\" formatter = \"TSV\" header = \"1\" uniqueRows = \"0\" count = \"\" datasetConfigVersion = \"0.6\" ><Dataset name = \"{{ var.biomartDataset }}\" interface = \"default\" ><Attribute name = \"ensembl_gene_id\" /><Attribute name = \"go_id\" /><Attribute name = \"go_linkage_type\" /><Attribute name = \"entrezgene_id\" /><Attribute name = \"namespace_1003\" /><Attribute name = \"name_1006\" /><Attribute name = \"kegg_enzyme\" /><Attribute name = \"transcript_length\" /></Dataset></Query>
